Update Texts and Info Pages
eoscostarica/proton-affiliate pull request #133
Opened 2021-08-07 23:56 UTC by xavier506

### What does this PR do?

- Resolve #127 
- Resolve #132 

### Steps to test

1. make run 
2. see About / Terms / Help pages

#### CheckList

- [] Follow proper Markdown format
- [] The content is adequate
- [] The content is available in both english and spanish
- [] I Ran a spell check

2021-08-08 15:58 UTC, adriexnet approved these changes
LGTM

2021-08-09 02:14 UTC, adriexnet requested changes

2021-08-09 02:14 UTC, adriexnet commented on webapp/src/routes/Terms/index.js
> +    //   showClauses={showClauses}
We should avoid commit commented code

2021-08-09 04:58 UTC, tetogomez commented on webapp/src/routes/Terms/index.js
> +    //   showClauses={showClauses}
lol

2021-08-09 05:01 UTC, tetogomez reviewed
LGTM

2021-08-09 16:08 UTC, xavier506 commented on webapp/src/routes/Terms/index.js
> +    //   showClauses={showClauses}
🆗

2021-08-09 23:09 UTC, closed without merging