feat(hapi): send rejection mail
eoscostarica/proton-affiliate pull request #357
Opened 2022-01-14 06:33 UTC by leisterfrancisco

### Send rejection email

### What does this PR do?

- Notify the user if they are rejected by KYC requirement

### Steps to test

1. `make run`

2022-01-14 17:16 UTC, xavier506 commented on hapi/src/utils/templates/mail.template.js
> +                      </p>
should we mention which countries have KYC available?


There is going to be an update soon to the proton wallet which enables many more countries for KYC , should we tell users about this?

2022-01-14 17:17 UTC, xavier506 commented on hapi/src/utils/templates/mail.template.js
> +                        To request joining the Referral Program, go to the Proton wallet app and submit your KYC application. If you're still having the same problem, please get in touch with us thro
If users are having trouble with KYC they should not be sent to our telegram as we dont handle KYC process

maybe we should send them to the general XPR chat

2022-01-14 17:18 UTC, xavier506 commented on hapi/src/utils/templates/mail.template.js
> +                          ${account} - Some News Regarding Your Proton On-Chain Referral Program Request
I would eliminate "Some News"

Regarding Your Proton On-Chain Referral Program Request

2022-01-14 17:21 UTC, xavier506 commented on webapp/src/routes/Admin/index.js
> +      // DON'T PLACE THIS CALL AFTER DELETE ACTION TO ENSURE THE USERS'S MAIL STILL EXIST
do we need this comment?

2022-01-14 17:22 UTC, xavier506 requested changes
view comments

2022-01-14 20:48 UTC, leisterfrancisco commented on hapi/src/utils/templates/mail.template.js
> +                        To request joining the Referral Program, go to the Proton wallet app and submit your KYC application. If you're still having the same problem, please get in touch with us thro
do you mean [this group](https://t.me/protonxpr)

2022-01-14 20:52 UTC, leisterfrancisco commented on hapi/src/utils/templates/mail.template.js
> +                          ${account} - Some News Regarding Your Proton On-Chain Referral Program Request
`${account} -` is a pattern used in the mail template, would you want me to update this pattern?

2022-01-14 20:53 UTC, leisterfrancisco commented on hapi/src/utils/templates/mail.template.js
> +                          ${account} - Some News Regarding Your Proton On-Chain Referral Program Request
Current template is:

`${account} -` ...........

2022-01-15 06:33 UTC, leisterfrancisco commented on hapi/src/utils/templates/mail.template.js
> +                      </p>
New content

2022-01-17 12:57 UTC, leisterfrancisco commented on hapi/src/utils/templates/mail.template.js
> +                          ${account} - Some News Regarding Your Proton On-Chain Referral Program Request
@xavier506 ?

2022-01-17 12:57 UTC, leisterfrancisco commented
![image](https://user-images.githubusercontent.com/28828796/149773241-e5aa8946-0a2b-41f2-ad8f-f755a4a87438.png)

@xavier506 this is how it looks now.

2022-01-19 03:12 UTC, leisterfrancisco commented
These PR changes will be included in a new PR.

2022-01-19 03:12 UTC, closed without merging