Feat/chore
eoscostarica/proton-affiliate pull request #383
Opened 2022-02-02 05:57 UTC by leisterfrancisco

### Chore tasks

### What does this PR do?

- Resolve #376 
- Resolve #377 

### Steps to test

1. `make run`

2022-02-02 05:58 UTC, leisterfrancisco commented on CONTRIBUTING.md
> +The following is a set of guidelines for contributing to Edenia's Open Source Projects and its packages, which are hosted in the [`edenia`](https://github.com/edenia) Organization on GitHub.
@xavier506 could you validate Edenia has it

2022-02-02 05:59 UTC, leisterfrancisco commented on LICENSE
> +Copyright (c) 2020 Edenia
@xavier506 please validate license is the same

2022-02-02 06:00 UTC, leisterfrancisco commented on README.md
> +Please read Edenia's [Open Source Contributing Guidelines](https://developers.eoscostarica.io/docs/open-source-guidelines).
@xavier506 This link is for EOS Costa Rica, is it ok?

2022-02-02 06:01 UTC, leisterfrancisco commented on README.md
> +Edenia is an independently-owned, self-funded, bare-metal Genesis block producer that provides stable and secure infrastructure for EOSIO blockchains. We support open source software for our communit
@xavier506 could you confirm me if this description could work for Edenia aswell

2022-02-02 06:01 UTC, leisterfrancisco commented on hapi/LICENSE
>  Permission is hereby granted, free of charge, to any person obtaining a copy
@xavier506 please check content is right for Edenia

2022-02-02 06:02 UTC, leisterfrancisco commented on hasura/LICENSE
> -Copyright (c) 2020 EOS Costa Rica
Same here

2022-02-02 06:02 UTC, leisterfrancisco commented on wallet/LICENSE
> -Copyright (c) 2020 EOS Costa Rica
Same here

2022-02-02 06:02 UTC, leisterfrancisco commented on webapp/LICENSE
> -Copyright (c) 2020 EOS Costa Rica
Same here

2022-02-02 13:29 UTC, xavier506 commented on CONTRIBUTING.md
> +The following is a set of guidelines for contributing to Edenia's Open Source Projects and its packages, which are hosted in the [`edenia`](https://github.com/edenia) Organization on GitHub.
edenia has a GitHub repo , for now we can just poiunt to the eos costa rica developer guidelines

2022-02-02 13:29 UTC, xavier506 commented on LICENSE
> +Copyright (c) 2020 Edenia
Yes MIT is fine , I would update date to 2022

2022-02-02 13:30 UTC, xavier506 commented on README.md
> +Please read Edenia's [Open Source Contributing Guidelines](https://developers.eoscostarica.io/docs/open-source-guidelines).
yes this is fine for now

2022-02-02 13:31 UTC, xavier506 commented on README.md
> +Please report bugs big and small by [opening an issue](https://github.com/edenia/proton-affiliate/issues)
Lets update this link to:

https://github.com/edenia/proton-affiliate/issues/new/choose

2022-02-02 13:33 UTC, xavier506 commented on README.md
> +Edenia is an independently-owned, self-funded, bare-metal Genesis block producer that provides stable and secure infrastructure for EOSIO blockchains. We support open source software for our communit
we should talk to luis diego about this and update this paragraph accordingly 

```
Edenia offers a suite of services to make the internet safer, more efficient, and transparent. Our team has been operating since 1987, leveraging the newest and most promising technologies over the past years.
We identify as technology agnostic builders with experience developing infrastructure and running nodes in different blockchain mainnets and testnets. Our goal is to push the boundaries of the network and leverage web3 for a greater good.```

2022-02-02 13:34 UTC, xavier506 commented on hapi/LICENSE
> +Copyright (c) 2020 Edenia
Maybe we should use the full company name for License 

**Sistemas Edenia Internacional S.A.**

2022-02-02 21:24 UTC, leisterfrancisco commented on README.md
> +Edenia is an independently-owned, self-funded, bare-metal Genesis block producer that provides stable and secure infrastructure for EOSIO blockchains. We support open source software for our communit
@xavier506 already @ldrojas is checking it

2022-02-02 21:28 UTC, leisterfrancisco commented on README.md
> +		<img src="https://github.com/edenia/eos-rate/raw/master/docs/eoscostarica-logo-black.png" width="300">
@xavier506 which image would it be?

2022-02-02 22:46 UTC, leisterfrancisco commented on README.md
> +Please read Edenia's [Open Source Contributing Guidelines](https://developers.eoscostarica.io/docs/open-source-guidelines).
@xavier506 is `Edenia` ok here? I mean, the contributing guidelines is from EOS Costa Rica, not Edenia, but not sure.

2022-02-02 22:50 UTC, leisterfrancisco commented on webapp/src/components/Footer/index.js
> +            href="https://github.com/edenia/proton-affiliate/releases"
@xavier506 Please, let me know if it is right

2022-02-02 22:50 UTC, leisterfrancisco commented on webapp/src/components/Footer/index.js
> +                href="https://github.com/edenia/proton-affiliate"
@xavier506 Please, let me know if it is right

2022-02-02 22:50 UTC, leisterfrancisco commented on webapp/src/components/Footer/index.js
> +            href="https://github.com/edenia/proton-affiliate/releases"
@xavier506 Please, let me know if it is right

2022-02-02 22:54 UTC, xavier506 commented on README.md
> +  - [About Sistemas Edenia Internacional S.A.](#about-sistemas-edenia-internacional-sa)
We can just use Edenia here 

About Edenia

2022-02-02 22:55 UTC, xavier506 commented on README.md
> +## About Sistemas Edenia Internacional S.A.
About Edenia (title is too long)

2022-02-02 22:58 UTC, xavier506 commented on README.md
> +		<img src="https://github.com/edenia/eos-rate/raw/master/docs/eoscostarica-logo-black.png" width="300">
![edenia-logo](https://user-images.githubusercontent.com/5632966/152251723-2bf96a5d-6c8c-432d-9395-470f7a0b7398.png)

2022-02-02 22:59 UTC, xavier506 commented on webapp/src/components/Footer/index.js
> +            href="https://github.com/edenia/proton-affiliate/releases"
yes this looks right

2022-02-02 22:59 UTC, xavier506 commented on webapp/src/components/Footer/index.js
> +                href="https://github.com/edenia/proton-affiliate"
yes looks good

2022-02-02 23:00 UTC, xavier506 commented on webapp/src/language/en.json
> +    "madeBy": "Made by Sistemas Edenia Internacional S.A. © 2022"
Our Brand is : Edenia 

The full legal name should only be  used in the license agreement

2022-02-02 23:00 UTC, xavier506 requested changes
@leisterfrancisco  please see comments

Our Brand is : Edenia 

The full legal name should only be  used in the license agreement

2022-02-15 19:55 UTC, xavier506 approved these changes
LGTM

2022-02-15 19:55 UTC, merged