Todos
eoscostarica/proton-affiliate pull request #76
Opened 2021-06-18 15:02 UTC by adriexnet

### Implement pending todos

### What does this PR do?

- Resolve #56
- Resolve #57

#### CheckList

- [x] Follow proper Markdown format
- [x] The content is adequate
- [x] The content is available in both english and spanish
- [x] I Ran a spell check

2021-06-18 16:10 UTC, xavier506 commented on contracts/affiliate/src/affiliate.cpp
> +  check(has_valid_kyc(admin), "userinfo for " + admin.to_string() + " it's not verified");
"KYC for " + admin.to_string() + " is not verified");

replace `it's` for `is `

`...is not verified`

 
 
 There is no need for an apostrophe here

example
**abbreviation**
it's time to go (abbreviation of it is)

**possessive**
It's main feature is performance 

feature belongs to something (le peretenece a algo)


https://www.grammarly.com/blog/its-vs-its/?&utm_source=google&utm_medium=cpc&utm_campaign=11907689446&utm_targetid=dsa-1233402314764&gclid=CjwKCAjwiLGGBhAqEiwAgq3q_mWTIJ02R83Z5sSZmGvlcJ2mKZQyG0p9eMZHD8iVCsdm9IoSA87BbBoCVg0QAvD_BwE&gclsrc=aw.ds

2021-06-18 16:11 UTC, xavier506 commented on contracts/affiliate/src/affiliate.cpp
> +  check(has_valid_kyc(user), "userinfo for " + user.to_string() + " it's not verified");
"KYC for " + admin.to_string() + " is not verified");

2021-06-18 16:12 UTC, xavier506 commented on contracts/affiliate/src/affiliate.cpp
> +  check(has_valid_kyc(invitee), "userinfo for " + invitee.to_string() + " it's not verified");
KYC for "account" is not verified

2021-06-18 16:13 UTC, xavier506 requested changes
@adriexnet  awesome work with the kyc method.

please see my comments about some grammar errors

2021-06-23 06:25 UTC, adriexnet commented on contracts/affiliate/src/affiliate.cpp
> +  check(has_valid_kyc(admin), "userinfo for " + admin.to_string() + " it's not verified");
@xavier506 thanks for the explication

2021-06-23 12:54 UTC, xavier506 approved these changes
LGTM

2021-06-23 12:54 UTC, merged